"""
Module: fusion_config.py

Purpose:
Default fallback configuration for the Knowledge Fusion Engine.

Runtime values should be read from ekr_runtime.runtime_configuration
through RuntimeConfigService. These values remain as safe defaults.
"""


class FusionConfig:

    COMPONENT_CODE = "KNOWLEDGE_FUSION"

    ENGINE_NAME = "KnowledgeFusionEngine"
    ENGINE_VERSION = "1.0"

    DEFAULTS = {
        "DIRECT_REFERENCE_SCORE": 100.0,
        "RESOLVED_THRESHOLD": 80.0,
        "POSSIBLE_MATCH_THRESHOLD": 60.0,
        "AMBIGUOUS_DELTA": 5.0,
        "NAME_SIMILARITY_WEIGHT": 0.35,
        "SEMANTIC_SIMILARITY_WEIGHT": 0.25,
        "DOMAIN_SIMILARITY_WEIGHT": 0.10,
        "PROFILE_COMPATIBILITY_WEIGHT": 0.15,
        "KNOWLEDGE_CONFIDENCE_WEIGHT": 0.15,
        "MAX_CANDIDATES_PER_KNOWLEDGE_ITEM": 25,
    }

    DIRECT_REFERENCE_SCORE = DEFAULTS["DIRECT_REFERENCE_SCORE"]
    RESOLVED_THRESHOLD = DEFAULTS["RESOLVED_THRESHOLD"]
    POSSIBLE_MATCH_THRESHOLD = DEFAULTS["POSSIBLE_MATCH_THRESHOLD"]
    AMBIGUOUS_DELTA = DEFAULTS["AMBIGUOUS_DELTA"]

    NAME_SIMILARITY_WEIGHT = DEFAULTS["NAME_SIMILARITY_WEIGHT"]
    SEMANTIC_SIMILARITY_WEIGHT = DEFAULTS["SEMANTIC_SIMILARITY_WEIGHT"]
    DOMAIN_SIMILARITY_WEIGHT = DEFAULTS["DOMAIN_SIMILARITY_WEIGHT"]
    PROFILE_COMPATIBILITY_WEIGHT = DEFAULTS["PROFILE_COMPATIBILITY_WEIGHT"]
    KNOWLEDGE_CONFIDENCE_WEIGHT = DEFAULTS["KNOWLEDGE_CONFIDENCE_WEIGHT"]

    MAX_CANDIDATES_PER_KNOWLEDGE_ITEM = DEFAULTS["MAX_CANDIDATES_PER_KNOWLEDGE_ITEM"]