CREATE SCHEMA IF NOT EXISTS omd_core;

CREATE SCHEMA IF NOT EXISTS omd_profile;

CREATE SCHEMA IF NOT EXISTS omd_ai;

CREATE SCHEMA IF NOT EXISTS omd_execution;

CREATE SCHEMA IF NOT EXISTS omd_semantic;