CREATE SCHEMA IF NOT EXISTS ekr_core;

CREATE SCHEMA IF NOT EXISTS ekr_profile;

CREATE SCHEMA IF NOT EXISTS ekr_ai;

CREATE SCHEMA IF NOT EXISTS ekr_execution;

CREATE SCHEMA IF NOT EXISTS ekr_semantic;