CREATE TABLE ekr_semantic.column_semantic
(
    column_semantic_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    column_id          BIGINT NOT NULL,
    semantic_type      VARCHAR(200),
    business_meaning   TEXT,
    business_domain    VARCHAR(200),
    is_pii             BOOLEAN NOT NULL DEFAULT FALSE,
    sensitivity_level  VARCHAR(100),
    is_key_candidate   BOOLEAN NOT NULL DEFAULT FALSE,
    key_type           VARCHAR(100),
    confidence_score   NUMERIC(10,4),
    detection_method   VARCHAR(100),
    reasoning          TEXT,
    semantic_json      JSONB,
    reasoning_json     JSONB,
    created_at         TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_column_semantic_column
        FOREIGN KEY (column_id)
        REFERENCES ekr_core."column"(column_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_column_semantic_column
        UNIQUE (column_id)
);

CREATE INDEX idx_column_semantic_column
ON ekr_semantic.column_semantic(column_id);

CREATE INDEX idx_column_semantic_type
ON ekr_semantic.column_semantic(semantic_type);

CREATE INDEX idx_column_semantic_domain
ON ekr_semantic.column_semantic(business_domain);

CREATE INDEX idx_column_semantic_pii
ON ekr_semantic.column_semantic(is_pii);

CREATE INDEX idx_column_semantic_key_candidate
ON ekr_semantic.column_semantic(is_key_candidate);

COMMENT ON SCHEMA ekr_semantic IS
'Stores semantic understanding generated by the Semantic Engine.';

COMMENT ON TABLE ekr_semantic.column_semantic IS
'Stores semantic meaning, business interpretation, PII detection, key detection and confidence for discovered enterprise asset columns.';

COMMENT ON COLUMN ekr_semantic.column_semantic.column_semantic_id IS
'Primary key for the semantic classification record.';

COMMENT ON COLUMN ekr_semantic.column_semantic.column_id IS
'Column from ekr_core.column being semantically analysed.';

COMMENT ON COLUMN ekr_semantic.column_semantic.semantic_type IS
'Inferred semantic type, for example INVOICE_IDENTIFIER, CUSTOMER_IDENTIFIER, AMOUNT, DATE, STATUS or EMAIL.';

COMMENT ON COLUMN ekr_semantic.column_semantic.business_meaning IS
'Human-readable explanation of what the column likely represents in business terms.';

COMMENT ON COLUMN ekr_semantic.column_semantic.business_domain IS
'Inferred business domain context from semantic analysis. This complements, but does not replace, ekr_business.business_domain.';

COMMENT ON COLUMN ekr_semantic.column_semantic.is_pii IS
'Indicates whether the column may contain personally identifiable information.';

COMMENT ON COLUMN ekr_semantic.column_semantic.sensitivity_level IS
'Inferred sensitivity level, for example PUBLIC, INTERNAL, CONFIDENTIAL or RESTRICTED.';

COMMENT ON COLUMN ekr_semantic.column_semantic.is_key_candidate IS
'Indicates whether the column appears to be a potential identifier, key or join candidate.';

COMMENT ON COLUMN ekr_semantic.column_semantic.key_type IS
'Inferred key type, for example BUSINESS_KEY, TECHNICAL_KEY, FOREIGN_KEY or NATURAL_KEY.';

COMMENT ON COLUMN ekr_semantic.column_semantic.confidence_score IS
'Confidence score assigned by the Semantic Engine.';

COMMENT ON COLUMN ekr_semantic.column_semantic.detection_method IS
'Method used by the Semantic Engine, for example RULE_BASED, AI_BASED or HYBRID.';

COMMENT ON COLUMN ekr_semantic.column_semantic.reasoning IS
'Human-readable reasoning explaining why the semantic classification was assigned.';

COMMENT ON COLUMN ekr_semantic.column_semantic.semantic_json IS
'Structured semantic payload including matched rules, candidates and profiling evidence.';

COMMENT ON COLUMN ekr_semantic.column_semantic.reasoning_json IS
'Additional structured reasoning payload reserved for future semantic explainability.';

COMMENT ON COLUMN ekr_semantic.column_semantic.created_at IS
'Timestamp when the semantic record was created.';

COMMENT ON COLUMN ekr_semantic.column_semantic.updated_at IS
'Timestamp when the semantic record was last updated.';