
BEGIN;
CREATE SCHEMA IF NOT EXISTS ekr_intelligence;
CREATE TABLE IF NOT EXISTS ekr_intelligence.enterprise_intelligence_assessment_comparison (
 assessment_comparison_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id BIGINT NOT NULL,
 business_domain_id BIGINT NOT NULL,
 previous_assessment_id BIGINT NOT NULL REFERENCES ekr_intelligence.enterprise_intelligence_assessment(assessment_id) ON DELETE CASCADE,
 current_assessment_id BIGINT NOT NULL REFERENCES ekr_intelligence.enterprise_intelligence_assessment(assessment_id) ON DELETE CASCADE,
 previous_version INTEGER NOT NULL,
 current_version INTEGER NOT NULL,
 new_object_count INTEGER NOT NULL DEFAULT 0,
 changed_object_count INTEGER NOT NULL DEFAULT 0,
 resolved_object_count INTEGER NOT NULL DEFAULT 0,
 unchanged_object_count INTEGER NOT NULL DEFAULT 0,
 confidence_delta NUMERIC(12,6),
 comparison_json JSONB NOT NULL DEFAULT '{}'::JSONB,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(previous_assessment_id,current_assessment_id)
);
CREATE TABLE IF NOT EXISTS ekr_intelligence.enterprise_intelligence_object_change (
 intelligence_object_change_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 assessment_comparison_id BIGINT NOT NULL REFERENCES ekr_intelligence.enterprise_intelligence_assessment_comparison(assessment_comparison_id) ON DELETE CASCADE,
 previous_intelligence_object_id BIGINT REFERENCES ekr_intelligence.enterprise_intelligence_object(intelligence_object_id) ON DELETE SET NULL,
 current_intelligence_object_id BIGINT REFERENCES ekr_intelligence.enterprise_intelligence_object(intelligence_object_id) ON DELETE SET NULL,
 object_type VARCHAR(50) NOT NULL,
 object_key VARCHAR(250) NOT NULL,
 change_type VARCHAR(30) NOT NULL CHECK(change_type IN ('NEW','CHANGED','RESOLVED','UNCHANGED')),
 title VARCHAR(500),
 previous_severity VARCHAR(30),
 current_severity VARCHAR(30),
 previous_confidence NUMERIC(12,6),
 current_confidence NUMERIC(12,6),
 confidence_delta NUMERIC(12,6),
 changed_fields JSONB NOT NULL DEFAULT '[]'::JSONB,
 change_summary TEXT,
 change_json JSONB NOT NULL DEFAULT '{}'::JSONB,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(assessment_comparison_id,object_type,object_key)
);
CREATE INDEX IF NOT EXISTS ix_ei_comparison_domain_current
ON ekr_intelligence.enterprise_intelligence_assessment_comparison(project_id,business_domain_id,current_version DESC);
CREATE INDEX IF NOT EXISTS ix_ei_change_comparison_type
ON ekr_intelligence.enterprise_intelligence_object_change(assessment_comparison_id,change_type,object_type);
CREATE SCHEMA IF NOT EXISTS ekr_runtime;
CREATE TABLE IF NOT EXISTS ekr_runtime.sapientia_bundle_version (
 bundle_code VARCHAR(100) PRIMARY KEY,
 installed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 bundle_metadata JSONB NOT NULL DEFAULT '{}'::JSONB
);
INSERT INTO ekr_runtime.sapientia_bundle_version(bundle_code,bundle_metadata)
VALUES ('enterprise_intelligence_platform_v1_bundle_3','{"migration":"112_enterprise_intelligence_assessment_evolution.sql"}'::JSONB)
ON CONFLICT(bundle_code) DO UPDATE SET installed_at=NOW(),bundle_metadata=EXCLUDED.bundle_metadata;
COMMIT;
