BEGIN;

CREATE SCHEMA IF NOT EXISTS ekr_knowledge;
CREATE SCHEMA IF NOT EXISTS ekr_intelligence;
CREATE SCHEMA IF NOT EXISTS ekr_runtime;

CREATE TABLE IF NOT EXISTS ekr_knowledge.enterprise_knowledge_version_comparison (
    knowledge_comparison_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    business_domain_id BIGINT NOT NULL REFERENCES ekr_business.business_domain(business_domain_id),
    previous_knowledge_version_id BIGINT NOT NULL REFERENCES ekr_knowledge.enterprise_knowledge_version(knowledge_version_id) ON DELETE CASCADE,
    current_knowledge_version_id BIGINT NOT NULL REFERENCES ekr_knowledge.enterprise_knowledge_version(knowledge_version_id) ON DELETE CASCADE,
    previous_version INTEGER NOT NULL,
    current_version INTEGER NOT NULL,
    added_item_count INTEGER NOT NULL DEFAULT 0,
    changed_item_count INTEGER NOT NULL DEFAULT 0,
    removed_item_count INTEGER NOT NULL DEFAULT 0,
    unchanged_item_count INTEGER NOT NULL DEFAULT 0,
    material_change_count INTEGER NOT NULL DEFAULT 0,
    change_summary TEXT,
    comparison_json JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(previous_knowledge_version_id, current_knowledge_version_id)
);

CREATE TABLE IF NOT EXISTS ekr_knowledge.enterprise_knowledge_item_change (
    knowledge_item_change_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_comparison_id BIGINT NOT NULL REFERENCES ekr_knowledge.enterprise_knowledge_version_comparison(knowledge_comparison_id) ON DELETE CASCADE,
    item_category VARCHAR(80) NOT NULL,
    item_key VARCHAR(500) NOT NULL,
    change_type VARCHAR(30) NOT NULL CHECK(change_type IN ('ADDED','CHANGED','REMOVED','UNCHANGED')),
    item_name VARCHAR(500),
    changed_fields JSONB NOT NULL DEFAULT '[]'::JSONB,
    change_summary TEXT,
    previous_json JSONB,
    current_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(knowledge_comparison_id, item_category, item_key)
);

CREATE INDEX IF NOT EXISTS ix_knowledge_comparison_domain_current
ON ekr_knowledge.enterprise_knowledge_version_comparison(project_id,business_domain_id,current_version DESC);

CREATE INDEX IF NOT EXISTS ix_knowledge_item_change_type
ON ekr_knowledge.enterprise_knowledge_item_change(knowledge_comparison_id,change_type,item_category);

CREATE TABLE IF NOT EXISTS ekr_runtime.sapientia_bundle_version (
    bundle_code VARCHAR(100) PRIMARY KEY,
    installed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    bundle_metadata JSONB NOT NULL DEFAULT '{}'::JSONB
);

INSERT INTO ekr_runtime.sapientia_bundle_version(bundle_code,bundle_metadata)
VALUES (
    'phase3_enterprise_intelligence_evolution',
    '{"migration":"114_phase3_enterprise_intelligence_evolution.sql","capabilities":["knowledge_delta","assessment_evolution","business_timeline","current_vs_assessed_status"]}'::JSONB
)
ON CONFLICT(bundle_code) DO UPDATE
SET installed_at=NOW(), bundle_metadata=EXCLUDED.bundle_metadata;

COMMIT;
