"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";

import { apiFetch } from "@/lib/api";
import Sidebar from "@/components/layout/Sidebar";
import RightPanel from "@/components/layout/RightPanel";
import MetricCard from "@/components/ui/MetricCard";

type DomainSummary = {
  datasets?: number;
  semantic_columns?: number;
  enterprise_concepts?: number;
  findings?: number;
};

type EnterpriseConcept = {
  enterprise_concept_id: number | string;
  concept_name?: string;
  concept_type?: string;
  confidence_score?: number | string;
  concept_description?: string;
  evidence_count?: number;
};

type IntelligenceFinding = {
  intelligence_finding_id: number | string;
  finding_type?: string;
  severity_level?: string;
  finding_title?: string;
  finding_description?: string;
  finding_interpretation?: string;
};

type DomainWorkspaceResponse = {
  summary?: DomainSummary;
  concepts?: EnterpriseConcept[];
  findings?: IntelligenceFinding[];
};

export default function DomainPage() {
  const params = useParams();
  const domain = String(params.domain);

  const [summary, setSummary] = useState<DomainSummary>({});
  const [concepts, setConcepts] = useState<EnterpriseConcept[]>([]);
  const [findings, setFindings] = useState<IntelligenceFinding[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    let cancelled = false;

    async function loadDomain() {
      setLoading(true);
      setError("");

      try {
        const data = await apiFetch<DomainWorkspaceResponse>(
          `/domains/${domain}/workspace`,
        );

        if (cancelled) {
          return;
        }

        setSummary(data.summary ?? {});
        setConcepts(data.concepts ?? []);
        setFindings(data.findings ?? []);
      } catch (err) {
        if (cancelled) {
          return;
        }

        setError(
          err instanceof Error
            ? err.message
            : "Sapientia could not load this business domain.",
        );
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    }

    loadDomain();

    return () => {
      cancelled = true;
    };
  }, [domain]);

  return (
    <main className="min-h-screen bg-[#f6f8fc]">
      <Sidebar />
      <RightPanel />

      <section className="ml-72 mr-96 p-10">
        <Link
          href="/dashboard"
          className="text-sm font-medium text-indigo-600"
        >
          ← Back to dashboard
        </Link>

        <div className="mb-10 mt-6">
          <p className="text-sm font-semibold uppercase tracking-widest text-indigo-600">
            Business Domain
          </p>

          <h1 className="mt-2 text-5xl font-bold text-slate-950">
            {domain}
          </h1>

          <p className="mt-3 text-slate-500">
            Enterprise concepts, findings and intelligence generated by
            Sapientia.
          </p>
        </div>

        {error && (
          <section className="mb-8 rounded-2xl border border-red-200 bg-red-50 p-5">
            <p className="font-semibold text-red-800">
              Sapientia could not load this domain
            </p>
            <p className="mt-2 text-sm text-red-700">{error}</p>
          </section>
        )}

        {loading ? (
          <section className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm">
            <p className="text-slate-500">
              Loading enterprise knowledge and intelligence...
            </p>
          </section>
        ) : (
          <>
            <div className="mb-8 grid grid-cols-1 gap-5 xl:grid-cols-4">
              <MetricCard
                label="Datasets"
                value={summary.datasets ?? 0}
              />
              <MetricCard
                label="Semantic Columns"
                value={summary.semantic_columns ?? 0}
              />
              <MetricCard
                label="Concepts"
                value={summary.enterprise_concepts ?? 0}
              />
              <MetricCard
                label="Findings"
                value={summary.findings ?? 0}
              />
            </div>

            <div className="mb-8 grid grid-cols-1 gap-6 xl:grid-cols-2">
              <Panel title="Enterprise Concepts">
                {concepts.length > 0 ? (
                  <div className="space-y-4">
                    {concepts.map((concept) => (
                      <div
                        key={concept.enterprise_concept_id}
                        className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-indigo-300"
                      >
                        <div className="flex justify-between gap-4">
                          <div>
                            <h3 className="text-xl font-bold text-slate-900">
                              {concept.concept_name ?? "Unnamed concept"}
                            </h3>

                            {concept.concept_type && (
                              <p className="mt-1 text-sm font-medium text-indigo-600">
                                {concept.concept_type}
                              </p>
                            )}
                          </div>

                          {concept.confidence_score !== undefined && (
                            <span className="h-fit rounded-full bg-indigo-50 px-3 py-1 text-sm text-indigo-700">
                              {concept.confidence_score}
                            </span>
                          )}
                        </div>

                        {concept.concept_description && (
                          <p className="mt-4 leading-6 text-slate-600">
                            {concept.concept_description}
                          </p>
                        )}

                        <p className="mt-4 text-sm text-slate-400">
                          Evidence records: {concept.evidence_count ?? 0}
                        </p>
                      </div>
                    ))}
                  </div>
                ) : (
                  <EmptyMessage>
                    No enterprise concepts are available for this domain yet.
                  </EmptyMessage>
                )}
              </Panel>

              <Panel title="AI Advisor">
                <div className="mb-5 rounded-2xl bg-gradient-to-r from-indigo-50 to-fuchsia-50 p-6">
                  <h3 className="mb-2 font-bold text-slate-900">
                    Ask about {domain}
                  </h3>

                  <p className="text-slate-600">
                    Sapientia answers using enterprise concepts, findings,
                    relationships and supporting intelligence.
                  </p>
                </div>

                <Link
                  href={`/domains/${domain}/ask`}
                  className="block rounded-xl bg-indigo-600 py-3 text-center font-semibold text-white transition hover:bg-indigo-500"
                >
                  Ask Sapientia
                </Link>
              </Panel>
            </div>

            <Panel title="Enterprise Intelligence Findings">
              {findings.length > 0 ? (
                <div className="space-y-3">
                  {findings.slice(0, 20).map((finding) => (
                    <div
                      key={finding.intelligence_finding_id}
                      className="rounded-2xl border border-slate-200 bg-slate-50 p-5"
                    >
                      <div className="mb-2 flex justify-between gap-4">
                        <p className="text-sm font-semibold text-indigo-600">
                          {finding.finding_type ?? "Insight"}
                        </p>

                        {finding.severity_level && (
                          <p className="rounded-full bg-slate-200 px-3 py-1 text-xs text-slate-600">
                            {finding.severity_level}
                          </p>
                        )}
                      </div>

                      <h3 className="font-bold text-slate-900">
                        {finding.finding_title ?? "Untitled finding"}
                      </h3>

                      {finding.finding_description && (
                        <p className="mt-2 leading-6 text-slate-600">
                          {finding.finding_description}
                        </p>
                      )}

                      {finding.finding_interpretation && (
                        <p className="mt-3 text-sm text-slate-500">
                          <span className="font-semibold">
                            Why it matters:
                          </span>{" "}
                          {finding.finding_interpretation}
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              ) : (
                <EmptyMessage>
                  No intelligence findings are available for this domain yet.
                </EmptyMessage>
              )}
            </Panel>
          </>
        )}
      </section>
    </main>
  );
}

function Panel({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
      <h2 className="mb-5 text-xl font-bold text-slate-900">{title}</h2>
      {children}
    </div>
  );
}

function EmptyMessage({ children }: { children: React.ReactNode }) {
  return (
    <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-6 text-sm text-slate-500">
      {children}
    </div>
  );
}